//! `daf init` — Initialize a new DAF project directory.
//!
//! Creates the canonical directory layout, a starter `daf.yml` configuration,
//! a sample agent manifest, and a sample playbook. Uses interactive prompts
//! when stdin is a TTY.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use console::style;
use dialoguer::{Confirm, Input};

use crate::Cli;

/// Arguments for `daf init`.
#[derive(Debug, clap::Args)]
pub struct InitArgs {
    /// Target directory (defaults to current working directory).
    #[arg(default_value = ".")]
    pub path: PathBuf,

    /// Project name override (default: directory name).
    #[arg(short, long)]
    pub name: Option<String>,

    /// Skip interactive prompts and use defaults.
    #[arg(long)]
    pub yes: bool,
}

/// Execute the `init` command.
pub async fn exec(args: &InitArgs, _cli: &Cli) -> Result<()> {
    let root = fs::canonicalize(&args.path).unwrap_or_else(|_| args.path.clone());
    let dir_name = root
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "daf-project".into());

    eprintln!(
        "{} Initializing DAF project in {}",
        style("[init]").cyan().bold(),
        style(root.display()).underlined(),
    );

    // ---- interactive prompts -------------------------------------------
    let project_name = if args.yes {
        args.name.clone().unwrap_or(dir_name)
    } else {
        Input::new()
            .with_prompt("Project name")
            .default(args.name.clone().unwrap_or(dir_name))
            .interact_text()?
    };

    let description: String = if args.yes {
        format!("{project_name} — a DAF agent project")
    } else {
        Input::new()
            .with_prompt("Description")
            .default(format!("{project_name} — a DAF agent project"))
            .interact_text()?
    };

    // Only advertise the implemented default; QUIC is not implemented.
    let transport = "tcp";

    let generate_samples = if args.yes {
        true
    } else {
        Confirm::new()
            .with_prompt("Generate sample agent and playbook?")
            .default(true)
            .interact()?
    };

    // Refuse existing outputs before creating any scaffold files.
    let mut outputs = vec!["daf.yml", ".gitignore", ".daf/.gitkeep", "mission.yml"];
    if generate_samples {
        outputs.extend([
            "agents/hello-worker.yml",
            "playbooks/setup.yml",
            "topologies/local.yml",
        ]);
    }
    for output in &outputs {
        if root.join(output).symlink_metadata().is_ok() {
            bail!(
                "Refusing to overwrite existing {}",
                root.join(output).display()
            );
        }
    }
    // JSON strings are valid YAML scalar strings; serialize user input instead
    // of interpolating quotes/newlines into the document.
    let project_name_yaml = serde_json::to_string(&project_name)?;
    let description_yaml = serde_json::to_string(&description)?;

    // ---- create directories --------------------------------------------
    let dirs = ["agents", "playbooks", "topologies", "logs"];
    for dir in &dirs {
        let p = root.join(dir);
        fs::create_dir_all(&p)
            .with_context(|| format!("failed to create directory: {}", p.display()))?;
        eprintln!("  {} {}/", style("+").green().bold(), dir);
    }

    // ---- write daf.yml -------------------------------------------------
    let config_content = format!(
        r#"# DAF project configuration
# Generated by `daf init`

project:
  name: {project_name_yaml}
  description: {description_yaml}
  version: "0.1.0"

cluster:
  transport: "{transport}"
  bind: "127.0.0.1:9400"
  max_agents: 64

logging:
  level: "info"
  format: "pretty"
  directory: "./logs"

vault:
  backend: "sled"
  path: ".daf/vault"

memory:
  backend: "local"
  path: ".daf/memory"
"#
    );
    write_file(&root.join("daf.yml"), &config_content)?;
    eprintln!("  {} daf.yml", style("+").green().bold());

    // ---- sample agent manifest -----------------------------------------
    if generate_samples {
        let agent_manifest = r#"# Sample agent manifest
# Future cluster manifest; agent spawning requires a connected backend.

agent:
  name: "hello-worker"
  kind: "worker"
  description: "A sample worker agent that echoes messages"

capabilities:
  - name: "echo"
    version: "1.0.0"
    description: "Echo back any message received"

resources:
  max_memory_bytes: 536870912   # 512 MiB
  max_cpu_ms: 300000            # 5 minutes
  max_connections: 16
  max_message_queue: 256

metadata:
  team: "platform"
  environment: "development"
"#;
        write_file(&root.join("agents/hello-worker.yml"), agent_manifest)?;
        eprintln!("  {} agents/hello-worker.yml", style("+").green().bold());

        let playbook = r#"# Sample configuration playbook
# Inspect with: daf configure check playbooks/setup.yml; execution requires a backend.

playbook:
  name: "initial-setup"
  description: "Configure agents for local development"

  tasks:
    - name: "Set log level"
      module: "config"
      targets: ["hello-worker"]
      params:
        logging.level: "debug"

    - name: "Health check"
      module: "health"
      targets: ["all"]
      params:
        timeout_ms: 5000
"#;
        write_file(&root.join("playbooks/setup.yml"), playbook)?;
        eprintln!("  {} playbooks/setup.yml", style("+").green().bold());

        let topology = r#"# Sample topology file
# Preview with: daf provision plan topologies/local.yml; apply requires a backend.

topology:
  name: "local-dev"
  description: "Single-node local development topology"

  nodes:
    - name: "local"
      address: "127.0.0.1:9400"
      roles: ["orchestrator", "worker"]

  agents:
    - manifest: "agents/hello-worker.yml"
      count: 2
      node: "local"
"#;
        write_file(&root.join("topologies/local.yml"), topology)?;
        eprintln!("  {} topologies/local.yml", style("+").green().bold());
    }

    write_file(
        &root.join("mission.yml"),
        r#"mission:
  name: hello-daf
  tasks:
    - name: hello
      agent: local
      params:
        command: ["echo", "Hello from DAF"]
"#,
    )?;

    // ---- .gitignore for DAF state --------------------------------------
    let gitignore = "# DAF local state\n.daf/\nlogs/*.log\n";
    write_file(&root.join(".daf/.gitkeep"), "")?;
    write_file(&root.join(".gitignore"), gitignore)?;
    eprintln!("  {} .gitignore", style("+").green().bold());

    eprintln!(
        "\n{} Project {} initialized successfully.",
        style("\u{2714}").green().bold(),
        style(&project_name).bold(),
    );
    eprintln!(
        "\n  Next steps:\n    {}  daf run mission.yml --yes\n    {}  daf provision plan topologies/local.yml\n",
        style("1.").dim(),
        style("2.").dim(),
    );

    Ok(())
}

/// Write a file, creating parent directories as needed.
fn write_file(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create parent dir for {}", path.display()))?;
    }
    use std::io::Write;
    let mut file = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .with_context(|| format!("refusing to overwrite or cannot create {}", path.display()))?;
    file.write_all(content.as_bytes())
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    fn cli() -> Cli {
        Cli::parse_from(["daf", "init", "--yes"])
    }

    #[tokio::test]
    async fn refuses_existing_project_without_overwriting() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join(".gitignore"), "precious\n").unwrap();
        let args = InitArgs {
            path: dir.path().into(),
            name: None,
            yes: true,
        };
        assert!(exec(&args, &cli()).await.is_err());
        assert_eq!(
            fs::read_to_string(dir.path().join(".gitignore")).unwrap(),
            "precious\n"
        );
        assert!(!dir.path().join("daf.yml").exists());
    }

    #[tokio::test]
    async fn generated_yaml_preserves_names_and_nested_samples() {
        let dir = tempfile::tempdir().unwrap();
        let name = "quoted \"name\"\ncluster: injected";
        let args = InitArgs {
            path: dir.path().into(),
            name: Some(name.into()),
            yes: true,
        };
        exec(&args, &cli()).await.unwrap();
        let config: serde_json::Value =
            serde_yaml_ng::from_str(&fs::read_to_string(dir.path().join("daf.yml")).unwrap())
                .unwrap();
        assert_eq!(config["project"]["name"], name);
        let playbook: serde_json::Value = serde_yaml_ng::from_str(
            &fs::read_to_string(dir.path().join("playbooks/setup.yml")).unwrap(),
        )
        .unwrap();
        assert_eq!(playbook["playbook"]["tasks"].as_array().unwrap().len(), 2);
        let topology: serde_json::Value = serde_yaml_ng::from_str(
            &fs::read_to_string(dir.path().join("topologies/local.yml")).unwrap(),
        )
        .unwrap();
        assert_eq!(topology["topology"]["nodes"].as_array().unwrap().len(), 1);
        assert!(dir.path().join("mission.yml").is_file());
        assert!(exec(&args, &cli()).await.is_err());
    }
}
