//! `daf init` — Initialize a new DAF project directory.
//!
//! Creates the canonical directory layout, a starter `daf.yml` configuration,
//! a sample agent manifest, and a sample playbook. Uses interactive prompts
//! when stdin is a TTY.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use console::style;
use dialoguer::{Confirm, Input, Select};

use crate::Cli;

/// Arguments for `daf init`.
#[derive(Debug, clap::Args)]
pub struct InitArgs {
    /// Target directory (defaults to current working directory).
    #[arg(default_value = ".")]
    pub path: PathBuf,

    /// Project name override (default: directory name).
    #[arg(short, long)]
    pub name: Option<String>,

    /// Skip interactive prompts and use defaults.
    #[arg(long)]
    pub yes: bool,
}

/// Execute the `init` command.
pub async fn exec(args: &InitArgs, _cli: &Cli) -> Result<()> {
    let root = fs::canonicalize(&args.path).unwrap_or_else(|_| args.path.clone());
    let dir_name = root
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "daf-project".into());

    eprintln!(
        "{} Initializing DAF project in {}",
        style("[init]").cyan().bold(),
        style(root.display()).underlined(),
    );

    // ---- interactive prompts -------------------------------------------
    let project_name = if args.yes {
        args.name.clone().unwrap_or(dir_name)
    } else {
        Input::new()
            .with_prompt("Project name")
            .default(args.name.clone().unwrap_or(dir_name))
            .interact_text()?
    };

    let description: String = if args.yes {
        format!("{project_name} — a DAF agent project")
    } else {
        Input::new()
            .with_prompt("Description")
            .default(format!("{project_name} — a DAF agent project"))
            .interact_text()?
    };

    let transport_choices = &["tcp", "unix", "quic"];
    let transport_idx = if args.yes {
        0
    } else {
        Select::new()
            .with_prompt("Default transport")
            .items(transport_choices)
            .default(0)
            .interact()?
    };
    let transport = transport_choices[transport_idx];

    let generate_samples = if args.yes {
        true
    } else {
        Confirm::new()
            .with_prompt("Generate sample agent and playbook?")
            .default(true)
            .interact()?
    };

    // ---- create directories --------------------------------------------
    let dirs = ["agents", "playbooks", "topologies", "logs"];
    for dir in &dirs {
        let p = root.join(dir);
        fs::create_dir_all(&p)
            .with_context(|| format!("failed to create directory: {}", p.display()))?;
        eprintln!("  {} {}/", style("+").green().bold(), dir);
    }

    // ---- write daf.yml -------------------------------------------------
    let config_content = format!(
        r#"# DAF project configuration
# Generated by `daf init`

project:
  name: "{project_name}"
  description: "{description}"
  version: "0.1.0"

cluster:
  transport: "{transport}"
  bind: "127.0.0.1:9400"
  max_agents: 64

logging:
  level: "info"
  format: "pretty"
  directory: "./logs"

vault:
  backend: "sled"
  path: ".daf/vault"

memory:
  backend: "local"
  path: ".daf/memory"
"#
    );
    write_file(&root.join("daf.yml"), &config_content)?;
    eprintln!("  {} daf.yml", style("+").green().bold());

    // ---- sample agent manifest -----------------------------------------
    if generate_samples {
        let agent_manifest = r#"# Sample agent manifest
# Place in agents/ and spawn with: daf agent spawn agents/hello-worker.yml

agent:
  name: "hello-worker"
  kind: "worker"
  description: "A sample worker agent that echoes messages"

capabilities:
  - name: "echo"
    version: "1.0.0"
    description: "Echo back any message received"

resources:
  max_memory_bytes: 536870912   # 512 MiB
  max_cpu_ms: 300000            # 5 minutes
  max_connections: 16
  max_message_queue: 256

metadata:
  team: "platform"
  environment: "development"
"#;
        write_file(&root.join("agents/hello-worker.yml"), agent_manifest)?;
        eprintln!("  {} agents/hello-worker.yml", style("+").green().bold());

        let playbook = r#"# Sample configuration playbook
# Run with: daf configure run playbooks/setup.yml

playbook:
  name: "initial-setup"
  description: "Configure agents for local development"

tasks:
  - name: "Set log level"
    module: "config"
    targets: ["hello-worker"]
    params:
      logging.level: "debug"

  - name: "Health check"
    module: "health"
    targets: ["all"]
    params:
      timeout_ms: 5000
"#;
        write_file(&root.join("playbooks/setup.yml"), playbook)?;
        eprintln!("  {} playbooks/setup.yml", style("+").green().bold());

        let topology = r#"# Sample topology file
# Apply with: daf provision apply topologies/local.yml

topology:
  name: "local-dev"
  description: "Single-node local development topology"

nodes:
  - name: "local"
    address: "127.0.0.1:9400"
    roles: ["orchestrator", "worker"]

agents:
  - manifest: "agents/hello-worker.yml"
    count: 2
    node: "local"
"#;
        write_file(&root.join("topologies/local.yml"), topology)?;
        eprintln!("  {} topologies/local.yml", style("+").green().bold());
    }

    // ---- .gitignore for DAF state --------------------------------------
    let gitignore = "# DAF local state\n.daf/\nlogs/*.log\n";
    write_file(&root.join(".daf/.gitkeep"), "")?;
    write_file(&root.join(".gitignore"), gitignore)?;
    eprintln!("  {} .gitignore", style("+").green().bold());

    eprintln!(
        "\n{} Project {} initialized successfully.",
        style("\u{2714}").green().bold(),
        style(&project_name).bold(),
    );
    eprintln!(
        "\n  Next steps:\n    {}  daf agent spawn agents/hello-worker.yml\n    {}  daf status\n",
        style("1.").dim(),
        style("2.").dim(),
    );

    Ok(())
}

/// Write a file, creating parent directories as needed.
fn write_file(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create parent dir for {}", path.display()))?;
    }
    fs::write(path, content)
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}
